create table bron.brk_stukdeel (
	id bigint primary key,
	brk_sdl_id varchar(60),
	nrn_sdl_id int,
	sdl_aard_stukdeel_code varchar(50),
	sdl_aard_stukdeel_oms text,
	sdl_koopsom double precision,
	sdl_koopsom_valuta varchar(50),
	brk_stk_id varchar(60),
	nrn_stk_id double precision,
	stk_akr_portefeuillenr varchar(16),
	tk_tijdstip_aanbieding varchar(20),
	stk_reeks_code varchar(50),
	stk_volgnummer double precision,
	stk_registercode_code varchar(50),
	stk_registercode_oms text,
	stk_soortregister_code varchar(50),
	stk_soortregister_oms text,
	tk_deel_soort varchar(5),
	brk_tng_id varchar(60),
	nrn_tng_id double precision,
	brk_atg_id varchar(60),
	nrn_atg_id double precision,
	brk_asg_vve varchar(60),
	ind_actueel varchar(5)
);

create table bron.brk_zakelijk_recht (
	id bigint primary key,
	brk_zrt_id varchar(60),
	nrn_zrt_id double precision,
	zrt_aardzakelijkrecht_code varchar(50),
	zrt_aardzakelijkrecht_oms text,
	zrt_aardzakelijkrecht_akr_code varchar(3),
	zrt_belast_azt text,
	zrt_belast_met_azt text,
	zrt_ontstaan_uit varchar(60),
	zrt_betrokken_bij varchar(60),
	zrt_isbeperkt_tot_tng double precision,
	zrt_betrekking_op_kot text,
	brk_kot_id varchar(60),
	nrn_kot_id double precision,
	nrn_kot_volgnr double precision,
	kot_akrkadgemeentecode_code varchar(50),
	kot_status_code varchar(50),
	kot_modification varchar(20),
	brk_tng_id varchar(60),
	nrn_tng_id double precision,
	tng_aandeel_teller double precision,
	tng_aandeel_noemer double precision,
	tng_einddatum varchar(20),
	tng_actueel varchar(5),
	nrn_asg_id double precision,
	asg_app_rechtsplitstype_code varchar(200),
	asg_app_rechtsplitstype_oms text,
	asg_einddatum char(20),
	asg_actueel char(20),
	brk_sjt_id varchar(60),
	sjt_bsn varchar(50),
	nrn_sjt_id double precision,
	sjt_beschikkingsbevoegdh_code varchar(50),
	sjt_beschikkingsbevoegdh_oms text,
	sjt_naam varchar(465),
	sjt_np_geboortedatum varchar(50),
	sjt_np_geboorteplaats varchar(80),
	sjt_np_geboorteland_code varchar(50),
	sjt_np_geboorteland_oms text,
	sjt_np_datumoverlijden varchar(50),
	sjt_nnp_rsin varchar(80),
	sjt_nnp_kvknummer varchar(8),
	sjt_nnp_rechtsvorm_code varchar(50),
	sjt_nnp_rechtsvorm_oms text,
	sjt_nnp_statutaire_naam varchar(200),
	sjt_nnp_statutaire_zetel varchar(24),
	brk_toestandsdatum_diva varchar(20)
);

create table bron.brk_kadastraal_object (
	id bigint primary key,
	brk_kot_id varchar(60),
	nrn_kot_id int,
	nrn_kot_volgnr int,
	kot_gemeentenaam varchar(50),
	kot_akrkadgemcode_code varchar(50),
	kot_kadastralegemeente_code text,
	kot_kad_gemeentecode varchar(50),
	kot_kad_gemeente_oms text,
	kot_sectie varchar(2),
	kot_perceelnummer int,
	kot_index_letter char(1),
	kot_index_nummer int,
	kot_soortgrootte_code varchar(50),
	kot_soortgrootte_oms text,
	kot_kadgrootte int,
	kot_relatie_g_perceel text,
	kot_koopsom int,
	kot_koopsom_valuta varchar(50),
	kot_koopjaar varchar(15),
	kot_indicatie_meer_objecten char(1),
	kot_cultuurcodeonbebouwd_code varchar(50),
	kot_cultuurcodeonbebouwd_oms text,
	kot_cultuurcodebebouwd_code text,
	kot_cultuurcodebebouwd_oms text,
	kot_akrregister9tekst text,
	kot_status_code varchar(50),
	kot_toestandsdatum varchar(16),
	kot_ind_voorlopige_kadgrens varchar(22),
	brk_sjt_id varchar(60),
	sjt_naam varchar(465),
	sjt_type varchar(23),
	sjt_np_geboortedatum varchar(50),
	sjt_np_geboorteplaats varchar(80),
	sjt_np_geboorteland_code varchar(50),
	sjt_np_geboorteland_oms text,
	sjt_np_datumoverlijden varchar(50),
	sjt_nnp_rsin varchar(80),
	sjt_nnp_kvknummer varchar(8),
	sjt_nnp_rechtsvorm_code varchar(50),
	sjt_nnp_rechtsvorm_oms text,
	sjt_nnp_statutaire_naam varchar(200),
	sjt_nnp_statutaire_zetel varchar(24),
	sjt_zrt text,
	sjt_aandeel varchar(81),
	sjt_vve_sjt_id varchar(60),
	sjt_vve_uit_eigendom varchar(465),
	kot_inonderzoek text,
	kot_modification varchar(16),
	kot_wktgeom text
);

create table bron.gvi_kot_aot (
	id bigint primary key,
	bron_id int,
	kot_id int,
	vot_id int,
	lps_id int,
	sps_id int,
	ingangsdatum_geldigheid varchar(16),
	einddatum_geldigheid varchar(16)
);
--
--
-- pok zoals aangeleverd door de WOZ
-- 
create table bron.pok_kot_aot (
	id bigint primary key,
	bron_id int,
	kot_kadastralegemeentecode varchar(5),
	kot_kadastralesectie varchar(2),
	kot_perceelnummer int,
	kot_objectindexletter char(1),
	kot_indexnummer int,
	vot_id int,
	ingangsdatum_geldigheid varchar(16),
	einddatum_geldigheid varchar(16)
);

 --
 --
 -- brk_bag zoals bedoeld in de producten, de formele bron
 --
 --
create table bron.brk_bag (
	id bigint primary key,
	brk_kot_id varchar(60),
	nrn_kot_id int,
	nrn_kot_volgnr int,
	kot_akrkadgemeentecode_code varchar(50),
	kot_akrkadgemeentecode_oms text,
	kot_sectie varchar(2),
	kot_perceelnummer int,
	kot_index_letter char(1),
	kot_index_nummer int,
	kot_status_code varchar(50),
	kot_modification varchar(16),
	bag_vot_id varchar(16),
	diva_vot_id int,
	diva_vot_statuscode varchar(3),
	diva_vot_ingangsdatum_cyclus varchar(16),
	diva_vot_einddatum_cyclus varchar(16),
	aot_openbareruimtenaam varchar(80),
	aot_huisnummer int,
	aot_huisletter char(1),
	aot_huisnummertoevoeging varchar(4),
	aot_postcode varchar(6),
	aot_woonplaatsnaam varchar(80),
	bron_relatie varchar(4)
);
 --
 --
 -- verblijfsobjecten 2016 inclusief historische cycli
 --
--
create table bron.bag_vot (
	id serial8 primary key,
	lv_bag_vot_id int,
	vot_diva_id int,
	brt_id int,
	nummer int,
	geometrie_sdo_gtype int,
	geometrie_sdo_srid int,
	rd_xcoord varchar(20),
	rd_ycoord varchar(20),
	geometrie_sdo_point_z int,
	status_geometrie varchar(3),
	gebruiksdoel_dmn varchar(4),
	oppervlakte int,
	documentdatum_mutatie varchar(20),
	documentnummer_mutatie varchar(20),
	statuscode varchar(3),
	broncode varchar(3),
	redenopvoercode varchar(3),
	redenafvoercode varchar(3),
	aantal_verhuurbare_eenheden int,
	cbs_nummer int,
	liggingcode varchar(3),
	gebruikscode varchar(4),
	aantal_bouwlagen int,
	type_woonobject_dmn varchar(2),
	eigendomsverhoudingcode varchar(2),
	financieringswijzecode varchar(3),
	ind_woningvoorraad char(1),
	aantal_kamers int,
	toegangscode varchar(3),
	locatieingangcode varchar(3),
	bouwlaagtoegang varchar(3),
	frontbreedte int,
	monumentcode varchar(3),
	ingangsdatum_cyclus varchar(20),
	einddatum_cyclus varchar(20),
	mutatiedatum varchar(20),
	opvoerdatum varchar(20),
	mutatie_gebruiker varchar(30),
	ind_vervallen char(1),
	ind_actueel char(1),
	objectcyclusnr int,
	indauthentiek char(1),
	indgeconstateerd char(1),
	indinonderzoek char(1)
);