create table bron.brp_stuf_csv (
  referentienummer character(13) not null,
  "Tijdstip bericht" bigint not null,
  mutatiesoort character(1) not null,
  "O_a_nummer" bigint,
  "O_bsn" bigint,
  "O_burgerlijkeStaat" integer,
  "O_geslachtsaanduiding" character(1),
  "O_geboortedatum" integer,
  "O_ind. Onvolledige datum" character(1),
  "O_datum_overlijden" integer,
  "O_plaatsVanOverlijden" varchar,
  "O_landVanOverlijden" varchar,
  "O_gemeenteVanInschrijving" integer,
  "O_datumInschrijvingGemeente" integer,
  "O_datumVestigingNederland" integer,
  "O_landVanImmigratie" integer,
  "O_vb" integer,
  "O_datumVerkrijgingvb" integer,
  "O_datumVerliesvb" integer,
  "O_land van emigratie" integer,
  "O_datumBeginRelatie" integer,
  "O_straatcode" integer,
  "O_huisnummer" integer,
  "O_huisletter" character(1),
  "O_huisnummer toevoeging" character(5),
  "O_aanduiding bij huisnummer" varchar,
  "O_Locatieomschrijving" varchar,
  "O_postcode" character(6),
  "O_mobielewoonruimtenaam" varchar,
  "O_mobielewoonruimtesoort" varchar,
  "O_buurtcode" integer,
  "O_wijkcode" integer,
  "O_deelgemeentecode" integer,
  "O_landcode" integer,
  "O_landcode corr adres" integer,
  "O_datum verkrijging nat1" integer,
  "O_datum verlies nat1" integer,
  "O_code nat1" integer,
  "O_datum verkrijging nat2" integer,
  "O_datum verlies nat2" integer,
  "O_code nat2" integer,
  "O_datum verkrijging nat3" integer,
  "O_datum verlies nat3" integer,
  "O_code nat3" integer,
  "O_datum verkrijging nat4" integer,
  "O_datum verlies nat4" integer,
  "O_code nat4" integer,
  "O_datum verkrijging nat5" integer,
  "O_datum verlies nat5" integer,
  "O_code nat5" integer,
  "O_datumOntbinding1" integer,
  "O_datumSluiting1" integer,
  "O_plaatsSluiting1" varchar,
  "O_landSluiting1" varchar,
  "O_soortVerbintenis1" character(1),
  "O_plaatsOntbinding1" varchar,
  "O_LandOntbinding1" varchar,
  "O_redenOntbinding1" character(1),
  "O_PartnerBSN1" integer,
  "O_PartnerGeboortedatum1" integer,
  "O_ind. Onvolledige datum1" character(1),
  "O_PartnerAnummer1" bigint,
  "O_datumOntbinding2" integer,
  "O_datumSluiting2" integer,
  "O_plaatsSluiting2" varchar,
  "O_landSluiting2" varchar,
  "O_soortVerbintenis2" character(1),
  "O_plaatsOntbinding2" varchar,
  "O_LandOntbinding2" varchar,
  "O_redenOntbinding2" character(1),
  "O_PartnerBSN2" integer,
  "O_PartnerGeboortedatum2" integer,
  "O_ind. Onvolledige datum2" character(1),
  "O_PartnerAnummer2" bigint,
  "O_datumOntbinding3" integer,
  "O_datumSluiting3" integer,
  "O_plaatsSluiting3" varchar,
  "O_landSluiting3" varchar,
  "O_soortVerbintenis3" character(1),
  "O_plaatsOntbinding3" varchar,
  "O_LandOntbinding3" varchar,
  "O_redenOntbinding3" character(1),
  "O_PartnerBSN3" integer,
  "O_PartnerGeboortedatum3" integer,
  "O_ind. Onvolledige datum3" character(1),
  "O_PartnerAnummer3" bigint,
  "O_datumOntbinding4" integer,
  "O_datumSluiting4" integer,
  "O_plaatsSluiting4" varchar,
  "O_landSluiting4" varchar,
  "O_soortVerbintenis4" character(1),
  "O_plaatsOntbinding4" varchar,
  "O_LandOntbinding4" varchar,
  "O_redenOntbinding4" character(1),
  "O_PartnerBSN4" integer,
  "O_PartnerGeboortedatum4" integer,
  "O_ind. Onvolledige datum4" character(1),
  "O_PartnerAnummer4" bigint,
  "O_datumOntbinding5" integer,
  "O_datumSluiting5" integer,
  "O_plaatsSluiting5" varchar,
  "O_landSluiting5" varchar,
  "O_soortVerbintenis5" character(1),
  "O_plaatsOntbinding5" varchar,
  "O_LandOntbinding5" varchar,
  "O_redenOntbinding5" character(1),
  "O_PartnerBSN5" integer,
  "O_PartnerGeboortedatum5" integer,
  "O_ind. Onvolledige datum5" character(1),
  "O_PartnerAnummer5" bigint,
  "O_Geboorteland ouder 1" integer,
  "O_Geboorteldatum_ouder1" integer,
  "O_Geboorteland ouder 2" integer,
  "O_Geboorteldatum_ouder2" integer,
  "N_a_nummer" bigint,
  "N_bsn" bigint,
  "N_burgerlijkeStaat" integer,
  "N_geslachtsaanduiding" character(1),
  "N_geboortedatum" integer,
  "N_ind. Onvolledige datum" character(1),
  "N_datum_overlijden" integer,
  "N_plaatsVanOverlijden" varchar,
  "N_landVanOverlijden" varchar,
  "N_gemeenteVanInschrijving" integer,
  "N_datumInschrijvingGemeente" integer,
  "N_datumVestigingNederland" integer,
  "N_landVanImmigratie" integer,
  "N_vb" integer,
  "N_datumVerkrijgingvb" integer,
  "N_datumVerliesvb" integer,
  "N_land van emigratie" integer,
  "N_datumBeginRelatie" integer,
  "N_straatcode" integer,
  "N_huisnummer" integer,
  "N_huisletter" character(1),
  "N_huisnummer toevoeging" character(5),
  "N_aanduiding bij huisnummer" varchar,
  "N_Locatieomschrijving" varchar,
  "N_postcode" character(6),
  "N_mobielewoonruimtenaam" varchar,
  "N_mobielewoonruimtesoort" varchar,
  "N_buurtcode" integer,
  "N_wijkcode" integer,
  "N_deelgemeentecode" integer,
  "N_landcode" integer,
  "N_landcode corr adres" integer,
  "N_datum verkrijging nat1" integer,
  "N_datum verlies nat1" integer,
  "N_code nat1" integer,
  "N_datum verkrijging nat2" integer,
  "N_datum verlies nat2" integer,
  "N_code nat2" integer,
  "N_datum verkrijging nat3" integer,
  "N_datum verlies nat3" integer,
  "N_code nat3" integer,
  "N_datum verkrijging nat4" integer,
  "N_datum verlies nat4" integer,
  "N_code nat4" integer,
  "N_datum verkrijging nat5" integer,
  "N_datum verlies nat5" integer,
  "N_code nat5" integer,
  "N_datumOntbinding1" integer,
  "N_datumSluiting1" integer,
  "N_plaatsSluiting1" varchar,
  "N_landSluiting1" varchar,
  "N_soortVerbintenis1" character(1),
  "N_plaatsOntbinding1" varchar,
  "N_LandOntbinding1" varchar,
  "N_redenOntbinding1" character(1),
  "N_PartnerBSN1" integer,
  "N_PartnerGeboortedatum1" integer,
  "N_ind. Onvolledige datum1" character(1),
  "N_PartnerAnummer1" bigint,
  "N_datumOntbinding2" integer,
  "N_datumSluiting2" integer,
  "N_plaatsSluiting2" varchar,
  "N_landSluiting2" varchar,
  "N_soortVerbintenis2" character(1),
  "N_plaatsOntbinding2" varchar,
  "N_LandOntbinding2" varchar,
  "N_redenOntbinding2" character(1),
  "N_PartnerBSN2" integer,
  "N_PartnerGeboortedatum2" integer,
  "N_ind. Onvolledige datum2" character(1),
  "N_PartnerAnummer2" bigint,
  "N_datumOntbinding3" integer,
  "N_datumSluiting3" integer,
  "N_plaatsSluiting3" varchar,
  "N_landSluiting3" varchar,
  "N_soortVerbintenis3" character(1),
  "N_plaatsOntbinding3" varchar,
  "N_LandOntbinding3" varchar,
  "N_redenOntbinding3" character(1),
  "N_PartnerBSN3" integer,
  "N_PartnerGeboortedatum3" integer,
  "N_ind. Onvolledige datum3" character(1),
  "N_PartnerAnummer3" bigint,
  "N_datumOntbinding4" integer,
  "N_datumSluiting4" integer,
  "N_plaatsSluiting4" varchar,
  "N_landSluiting4" varchar,
  "N_soortVerbintenis4" character(1),
  "N_plaatsOntbinding4" varchar,
  "N_LandOntbinding4" varchar,
  "N_redenOntbinding4" character(1),
  "N_PartnerBSN4" integer,
  "N_PartnerGeboortedatum4" integer,
  "N_ind. Onvolledige datum4" character(1),
  "N_PartnerAnummer4" bigint,
  "N_datumOntbinding5" integer,
  "N_datumSluiting5" integer,
  "N_plaatsSluiting5" varchar,
  "N_landSluiting5" varchar,
  "N_soortVerbintenis5" character(1),
  "N_plaatsOntbinding5" varchar,
  "N_LandOntbinding5" varchar,
  "N_redenOntbinding5" character(1),
  "N_PartnerBSN5" integer,
  "N_PartnerGeboortedatum5" integer,
  "N_ind. Onvolledige datum5" character(1),
  "N_PartnerAnummer5" bigint,
  "N_Geboorteland ouder 1" integer,
  "N_Geboorteldatum_ouder1" integer,
  "N_Geboorteland ouder 2" integer,
  "N_Geboorteldatum_ouder2" integer,
  "Onbekend" varchar
);

create index "stufcsv_Tijdstip bericht_idx" on bron.brp_stuf_csv("Tijdstip bericht");
create index stufcsv_n_a_nummer_idx on bron.brp_stuf_csv("N_a_nummer");
create index stufcsv_n_bsn_idx on bron.brp_stuf_csv("N_bsn");
create index stufcsv_n_postcode_idx on bron.brp_stuf_csv("N_postcode");
create index stufcsv_n_straatcode_idx on bron.brp_stuf_csv("N_straatcode");
create index stufcsv_o_a_nummer_idx on bron.brp_stuf_csv("O_a_nummer");
create index stufcsv_o_bsn_idx on bron.brp_stuf_csv("O_bsn");
create index stufcsv_o_postcode_idx on bron.brp_stuf_csv("O_postcode");
create index stufcsv_o_straatcode_idx on bron.brp_stuf_csv("O_straatcode");

